# Generated by Django 4.2.11 on 2024-04-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
